### ISSUE TITLE
Java error message when using own data

### ISSUE THREAD

**Issue by melnel000** [seppinho/mutation-server#26]
I can run mutation-server locally using the provided test data (input fastq files). However, when I use my own fastq files, I get the following error message (below). Can you offer any assistance on what the problem might be?

Exception in thread "main" java.lang.NullPointerException
       at genepi.mut.pileup.PileupToolLocal.run(PileupToolLocal.java:118)
       at genepi.base.Tool.start(Tool.java:193)
       at genepi.base.Toolbox.start(Toolbox.java:44)
       at genepi.mut.Server.main(Server.java:42)

**Comment by haansi** [comment]
Hi there, can you please provide the commands you are trying to execute for both files?

**Comment by melnel000** [comment]
These are the commands I am using:

# Map mitochondrial reads to mitochondrial genome

/opt/exp_soft/bwa-0.7.12/bwa mem /home/melnel000/mtDNA-server/rCRS.fasta \
/home/melnel000/mtDNA-server/MTS81_S2_L001_R1_001.fastq_1.gz /home/melnel000/mtDNA-server/MTS81_S2_L001_R2_001.fastq_1.gz \
/home/melnel000/mtDNA-server/MTS81.sam

# Convert sam to bam file, sort and index

/usr/bin/samtools view -bS /home/melnel000/mtDNA-server/MTS81.sam | samtools sort - /home/melnel000/mtDNA-server/MTS81_sorted \
/usr/bin/samtools index /home/melnel000/mtDNA-server/MTS81_sorted.bam

/opt/exp_soft/java/jdk1.8.0_31/bin/java -jar /home/melnel000/mtDNA-server/mutation-server-1.1.9.jar analyse-local --input \
/home/melnel000/mtDNA-server/home/melnel000/mtDNA-server/MTS81_sorted.bam --indel --output /home/melnel000/mtDNA-server/MTS81_sorted_results \
--reference /home/melnel000/mtDNA-server/rCRS.fasta --level 0.01

When I run the same script with the small_r1.fastq and small_r2.fastq files I get an output file.

Thanks for the assistance
