### ISSUE TITLE
Indels in VCF

### ISSUE THREAD

**Issue by haansi** [seppinho/mutation-server#27]
Indel: true
Write VCF: true

```
Exception in thread "main" java.lang.NumberFormatException: For input string: "311.1"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.lang.Integer.parseInt(Integer.java:580)
	at java.lang.Integer.parseInt(Integer.java:615)
	at genepi.io.table.reader.AbstractTableReader.getInteger(AbstractTableReader.java:49)
	at genepi.io.table.reader.AbstractTableReader.getInteger(AbstractTableReader.java:29)
	at genepi.mut.util.MutationServerReader.parse(MutationServerReader.java:38)
	at genepi.mut.util.MutationServerReader.parse(MutationServerReader.java:18)
	at genepi.mut.util.VcfWriter.createVCF(VcfWriter.java:40)
	at genepi.mut.pileup.PileupToolLocal.run(PileupToolLocal.java:236)
	at genepi.base.Tool.start(Tool.java:193)
	at genepi.base.Toolbox.start(Toolbox.java:44)
	at genepi.mut.Server.main(Server.java:42)

```

**Comment by seppinho** [comment]
Indels still excluded but no null pointer anymoer
