### ISSUE TITLE
Java Memory Exception

### ISSUE THREAD

**Issue by jdpleiness** [seppinho/mutation-server#28]
Command run:
```Bash
java -jar mutation-server-1.1.11.jar analyse-local --input <my-sample>.mt.bam --output test-output/ --reference hs38DH.fa --level 0.01 --writeVcf
```

```
Input Folder: <my-sample>.mt.bam
Output Folder: /test-output
Detection limit: 0.01
Base Quality: 20
Map Quality: 20
Alignment Quality: 30
BAQ: true
Indel: false
Write VCF: true
```
Produces the following error:
```
Exception in thread "main" java.lang.OutOfMemoryError
    at java.lang.AbstractStringBuilder.hugeCapacity(AbstractStringBuilder.java:161)
    at java.lang.AbstractStringBuilder.newCapacity(AbstractStringBuilder.java:155)
    at java.lang.AbstractStringBuilder.ensureCapacityInternal(AbstractStringBuilder.java:125)
    at java.lang.AbstractStringBuilder.append(AbstractStringBuilder.java:448)
    at java.lang.StringBuilder.append(StringBuilder.java:136)
    at genepi.mut.util.ReferenceUtil.readInReference(ReferenceUtil.java:63)
    at genepi.mut.pileup.BamAnalyser.<init>(BamAnalyser.java:79)
    at genepi.mut.pileup.PileupToolLocal.run(PileupToolLocal.java:200)
    at genepi.base.Tool.start(Tool.java:193)
    at genepi.base.Toolbox.start(Toolbox.java:44)
    at genepi.mut.Server.main(Server.java:42)
```
I have also increased the Java max heap size to 200Gb and received the same results.

**Comment by seppinho** [comment]
Please specify the mt reference, available e.g. here:
https://github.com/seppinho/mutation-server/tree/master/test-data/mtdna/mixtures/reference
